server:
    port: 8080
spring:
    batch:
        initialize-schema: always
    datasource:
        driverClassName: org.h2.Driver
        initialization-mode: always
        password: ''
        url: jdbc:h2:mem:steps;DB_CLOSE_DELAY=-1
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-db-console
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true
logging:
    level:
        org:
            hibernate: info